import { useEffect, useState } from 'react';
import { Activity, AlertTriangle, CheckCircle, Bell, Eye, X } from 'lucide-react';
import { MetricCard, DonutChart, BarChart, LineChart } from '@/components/charts';
import { getState, subscribe, generateAlerts, acknowledgeAlert } from '@/lib/store';
import type { Alert } from '@/lib/types';

export function MonitoringPage() {
  const [state, setLocalState] = useState(getState());
  const [filter, setFilter] = useState<'all' | 'open' | 'acknowledged'>('all');

  useEffect(() => {
    const unsub = subscribe(() => setLocalState(getState()));
    setLocalState(getState());
    return unsub;
  }, []);

  if (!state.isGenerated) {
    return (
      <div className="text-center py-20 text-gray-400">
        <Activity size={48} className="mx-auto mb-4 opacity-50" />
        <p>Generate a dataset and run detection to monitor alerts.</p>
      </div>
    );
  }

  const alerts = state.alerts.length > 0 ? state.alerts : generateAlerts();
  const unacknowledged = alerts.filter(a => !a.acknowledged);
  const acknowledged = alerts.filter(a => a.acknowledged);

  const filteredAlerts = filter === 'all' ? alerts :
    filter === 'open' ? unacknowledged : acknowledged;

  const severityData = ['low', 'medium', 'high', 'critical'].map(sev => ({
    label: sev.charAt(0).toUpperCase() + sev.slice(1),
    value: alerts.filter(a => a.severity === sev).length,
    color: sev === 'critical' ? '#ef4444' :
           sev === 'high' ? '#f97316' :
           sev === 'medium' ? '#f59e0b' : '#9ca3af',
  }));

  const alertsByUser = Array.from(new Set(alerts.map(a => a.user_id))).map(uid => ({
    label: uid,
    value: alerts.filter(a => a.user_id === uid).length,
  })).sort((a, b) => b.value - a.value).slice(0, 10);

  const alertsTimeline = getAlertTimeline(alerts);

  return (
    <div className="space-y-6">
      <div className="grid grid-cols-2 lg:grid-cols-4 gap-4">
        <MetricCard
          label="Total Alerts"
          value={alerts.length}
          icon={Bell}
          color="blue"
          subtitle="Generated by detection engine"
        />
        <MetricCard
          label="Active Alerts"
          value={unacknowledged.length}
          icon={AlertTriangle}
          color="red"
          subtitle="Awaiting acknowledgment"
        />
        <MetricCard
          label="Acknowledged"
          value={acknowledged.length}
          icon={CheckCircle}
          color="green"
          subtitle="Reviewed by analyst"
        />
        <MetricCard
          label="Critical Severity"
          value={alerts.filter(a => a.severity === 'critical').length}
          icon={AlertTriangle}
          color="amber"
          subtitle="Highest priority"
        />
      </div>

      <div className="grid grid-cols-1 lg:grid-cols-3 gap-6">
        <div className="rounded-xl border border-gray-200 bg-white p-6 shadow-sm">
          <h3 className="font-semibold text-gray-900 mb-4">Alerts by Severity</h3>
          <DonutChart
            data={severityData}
            centerLabel="Alerts"
            centerValue={alerts.length.toString()}
          />
        </div>

        <div className="lg:col-span-2 rounded-xl border border-gray-200 bg-white p-6 shadow-sm">
          <h3 className="font-semibold text-gray-900 mb-4">Alert Timeline</h3>
          <LineChart
            data={alertsTimeline}
            height={260}
            color="#ef4444"
            yLabel="Alerts per day"
          />
        </div>
      </div>

      <div className="rounded-xl border border-gray-200 bg-white p-6 shadow-sm">
        <h3 className="font-semibold text-gray-900 mb-4">Alerts per User</h3>
        <BarChart data={alertsByUser} height={240} />
      </div>

      <div className="rounded-xl border border-gray-200 bg-white shadow-sm overflow-hidden">
        <div className="px-6 py-4 border-b border-gray-100 flex items-center justify-between">
          <div className="flex items-center gap-2">
            <Bell size={18} className="text-gray-400" />
            <h3 className="font-semibold text-gray-900">Alert Queue</h3>
          </div>
          <div className="flex gap-1">
            {(['all', 'open', 'acknowledged'] as const).map(f => (
              <button
                key={f}
                onClick={() => setFilter(f)}
                className={`px-3 py-1.5 rounded-lg text-xs font-medium transition-colors ${
                  filter === f
                    ? 'bg-blue-100 text-blue-700'
                    : 'text-gray-500 hover:bg-gray-100'
                }`}
              >
                {f.charAt(0).toUpperCase() + f.slice(1)}
              </button>
            ))}
          </div>
        </div>

        {filteredAlerts.length === 0 ? (
          <div className="py-16 text-center text-gray-400">
            <CheckCircle size={32} className="mx-auto mb-2 opacity-50" />
            <p className="text-sm">No alerts in this category</p>
          </div>
        ) : (
          <div className="max-h-[500px] overflow-y-auto">
            {filteredAlerts.map((alert, i) => (
              <AlertRow
                key={i}
                alert={alert}
                onAcknowledge={() => acknowledgeAlert(alert.id)}
              />
            ))}
          </div>
        )}
      </div>
    </div>
  );
}

function AlertRow({ alert, onAcknowledge }: { alert: Alert; onAcknowledge: () => void }) {
  const [expanded, setExpanded] = useState(false);

  const severityColors = {
    critical: { bg: 'bg-red-50', border: 'border-l-red-500', text: 'text-red-700', badge: 'bg-red-100 text-red-700' },
    high: { bg: 'bg-orange-50', border: 'border-l-orange-500', text: 'text-orange-700', badge: 'bg-orange-100 text-orange-700' },
    medium: { bg: 'bg-amber-50', border: 'border-l-amber-500', text: 'text-amber-700', badge: 'bg-amber-100 text-amber-700' },
    low: { bg: 'bg-gray-50', border: 'border-l-gray-400', text: 'text-gray-600', badge: 'bg-gray-100 text-gray-600' },
  };

  const c = severityColors[alert.severity];

  return (
    <div className={`border-l-4 ${c.border} ${c.bg} border-b border-gray-100`}>
      <div
        className="px-6 py-3 flex items-center gap-4 cursor-pointer"
        onClick={() => setExpanded(!expanded)}
      >
        <AlertTriangle size={16} className={c.text} />
        <div className="flex-1 min-w-0">
          <div className="flex items-center gap-2">
            <span className="font-mono text-sm font-medium text-gray-800">{alert.user_id}</span>
            <span className={`text-[10px] font-bold px-2 py-0.5 rounded-full ${c.badge}`}>
              {alert.severity.toUpperCase()}
            </span>
            {alert.acknowledged && (
              <span className="text-[10px] font-bold px-2 py-0.5 rounded-full bg-green-100 text-green-700">
                ACKNOWLEDGED
              </span>
            )}
          </div>
          <p className="text-xs text-gray-600 mt-1 truncate">{alert.message}</p>
        </div>
        <span className="text-xs text-gray-400 flex-shrink-0">
          {new Date(alert.timestamp).toLocaleString()}
        </span>
        <button
          onClick={(e) => { e.stopPropagation(); setExpanded(!expanded); }}
          className="p-1.5 rounded-lg hover:bg-white/50"
        >
          <Eye size={14} className="text-gray-400" />
        </button>
      </div>
      {expanded && (
        <div className="px-6 pb-3 pt-1">
          <div className="bg-white rounded-lg p-3 text-xs text-gray-600">
            <p className="mb-2">{alert.message}</p>
            <div className="flex gap-4 text-gray-400">
              <span>Alert ID: <span className="font-mono">{alert.id}</span></span>
              <span>Severity: <span className="font-medium">{alert.severity}</span></span>
            </div>
            {!alert.acknowledged && (
              <button
                onClick={(e) => { e.stopPropagation(); onAcknowledge(); }}
                className="mt-3 flex items-center gap-1.5 bg-blue-600 hover:bg-blue-700 text-white text-xs font-medium px-3 py-1.5 rounded-lg transition-colors"
              >
                <CheckCircle size={14} />
                Acknowledge Alert
              </button>
            )}
          </div>
        </div>
      )}
    </div>
  );
}

function getAlertTimeline(alerts: Alert[]) {
  const byDate = new Map<string, number>();
  for (const a of alerts) {
    const date = new Date(a.timestamp).toLocaleDateString('en-US', { month: 'short', day: 'numeric' });
    byDate.set(date, (byDate.get(date) || 0) + 1);
  }
  return Array.from(byDate.entries()).map(([label, value]) => ({ label, value }));
}
